<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>PbBench</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Z3.Linq\Z3.Linq.csproj" />
  </ItemGroup>
</Project>
